### ISSUE TITLE
Which is the commercial version?

### ISSUE THREAD

**Issue by vasco3** [MichaelWehar/Open-Source-Spell-Checker#2]

**Comment by MichaelWehar** [comment]
Thank you so much for submitting the issue!

(1) This repository was created to be a free client-side spell checker that anyone can use and contribute to.  I used variations of it in a few non-commercial websites.

(2) I recently stopped contributing code to this repository to take a project developing a commercial spell checker.  We will be looking for beta testers and early adopters and I welcome anyone who might be interested to contact me via email: dff72324@gmail.com

Thank you and I hope that you have a nice weekend!

**Comment by MichaelWehar** [comment]
The commercial spell checker is currently in beta.  If you would like to give it a try, please contact: michael.w@wordreference.com
